version: '3'
services:
  webfront:
    build:
      dockerfile: ./webfront/Dockerfile
    volumes:
      - ./webfront:/usr/src/app # ローカルとコンテナ内の同期
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true