version: '3'
services:
  webfront:
    build:
      dockerfile: ./webfront/Dockerfile
    volumes:
      - ./webfront:/usr/src/app # ローカルとコンテナ内の同期
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/go/src/app
      - go-pkg:/go/pkg
      - go-bin:/go/bin
    # command: go run cmd/main.go
    command: /bin/sh
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_dev
    ports:
      - "3306:3306"

volumes:
  go-pkg:
  go-bin: