// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/yito0424/pop-up-todo/backend/configs"
	"github.com/yito0424/pop-up-todo/backend/internal/externalinterface/db"
	"github.com/yito0424/pop-up-todo/backend/internal/externalinterface/server"
	"github.com/yito0424/pop-up-todo/backend/internal/interfaceadapter/controller"
	"github.com/yito0424/pop-up-todo/backend/internal/interfaceadapter/repository"
	"github.com/yito0424/pop-up-todo/backend/internal/usecase"
)

// Injectors from wire.go:

func InitializeServer(config configs.Config) (server.Server, func()) {
	sqlHandler := db.NewSqlHandler(config)
	userRepository := repository.NewUserRepository(sqlHandler)
	userUsecase := usecase.NewUserUsecase(userRepository, config)
	userController := controller.NewUserController(userUsecase)
	serverServer := server.NewServer(userController)
	return serverServer, func() {
	}
}
